### ISSUE TITLE
Code example has 'from app_data.payments' vs. 'from {{ ref('raw_payments') }}'

### ISSUE THREAD

**Issue by seanofahey** [dbt-labs/docs.getdbt.com#107]
One of the code examples on the using [Jinga page](https://docs.getdbt.com/docs/writing-code-in-dbt/using-jinja/) (last one before the "Write modular macros" section) uses 'from app_data.payments' vs. 'from {{ ref('raw_payments') }}' which throws an error when used with the prior part of the tutorial.

Runtime Error in model order_payment_method_amounts (models/order_payment_method_amounts.sql)
    404 Not found: Dataset dbt-tutorial-274612:app_data was not found in location US

**Comment by clrcrl** [comment]
Hi @seanofahey — the Jinja tutorial was written before we created the Getting Started tutorial, so it makes sense that they aren't aligned.

I think the best move forward is to move the Jinja tutorial over to tutorial section. We're currently re-working a lot of the structure of the docs, this is definitely something I'd like to do but not a high priority. I'd accept a PR that moves it over though and updates the code.
