### ISSUE TITLE
Update dbt Cloud docs V1

### ISSUE THREAD

**Issue by amychen1776** [dbt-labs/docs.getdbt.com#156]
Here is the list of the things that we can quickly update to make the dbt Cloud docs easier to understand:

- Overview page --> should actually have a burb at the top with a quick overview of what dbt cloud is (versus dbt Core)
- Update the screenshots for the `dbt Cloud Quickstart` page to take into account the new create a project flow
- update the links in the `dbt Cloud Quickstart` page 
- Redo the connect a repo section with links to the different ways to set up your repo connection ([link to this link](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-import-a-project-by-git-url))
- Update screenshot for `Using a dbt Cloud managed repository` page
- Update `Connecting your GitHub Account` so users fully understand they need to setup the dbt cloud app on their github organization

**Comment by alexbethea22** [comment]
SETTING UP SLACK NOTIFICATIONS!!
