### ISSUE TITLE
Improvements to "Reference > dbt Jinja Functions" section

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#241]
Leaving this as a place to come back to.

We could do a ton to improve [this section](https://docs.getdbt.com/reference/dbt-jinja-functions). Things that come to mind:
- Properly documenting each function — some are well documented, others aren't. Each function should have headings like:
```
# var

{{ var(variable_name, default_value=None) }}

## Description
Returns a project variable, as defined in your `dbt_project.yml`, or via the command line

## Related documentation
- Using variables

## Arguments
(ok probably not needed here)
### variable_name (required)

### default_value
An optional default value. Note that if this variable is not present, a compilation error will be thrown.

## Examples
### Limit data based on a variable
...
### Other more complicated example
...
```

- Generate these definitions by documenting the macros in dbt-core
- Group the functions better. This gets grey, but I think there's a broad categorization e.g.:
     - blocks: `doc`, `snapshot` etc.
     - macros that do things: `run_query`, `tojson`, `toyaml` — in my mind, things that make sense inside of `{% do ... %}` blocks
     - variables that return a thing (generally don't have any arguments): `target`, `var` (arguably a function), `project_name`, `invocation_id`, `this`
     - filters: `as_text`
     - ??? statements (what is a statement anyway, is it a macro? why do you have to `call` it?)
- document the context each object is available in — at the moment we have some "floating" articles about contexts, some of which contain extra Jinja objects, but I'd prefer to have this information listed in the "function" pages, like "oh schema is only available in an `on-run-end` context"
- Generate the list of functions (i.e. just iterate over the sub-directory), and also use yaml front-matter for a short description

**Comment by runleonarun** [comment]
Moving this idea to an [internal project](https://www.notion.so/dbtlabs/Content-Improvements-ae458c447cfa4eceb8b9d4eb33551654). We will reopen when this project is on our roadmap.
