### ISSUE TITLE
Improvements to "Reference > commands" section

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#244]
We can do a lot to improve this section:
- Use a (yet-to-be-made) CLI react component (see #171)
- Ensure each command has robust docs, like so:

```
# clean
## description
The `clean` is a utility function that deletes all folders specified in the [clean-targets](clean-targets) list specified in your `dbt_project.yml` file. This is useful for deleting installed packages in the `dbt_modules` directory, and compiled files in the `target` directory.

## Options (flags?)
This flag has no options

## Examples
(use the examples from the `clean-targets` docs

```
- List each flag under a `command flags` section. Each article should list the commands that the flag applies to (this is especially important now that people run commands from dbt Cloud), and whether it is CLI only, or also works in Cloud
     - `--models (-m), --select (-s) and --exclude`
     - `--vars`
     - `--target (-t) (CLI only)`
     - `--fail-fast (-x)`
     - `--no-version-check`
     - etc

```
# --target (-t) (CLI only)
``
$ dbt <command> --target [<target_name>](target_name)
$ dbt <command> -t [<target_name>](target_name)
``
## Description
Switch the target you're using for this command

## Commands
- `run`
- `test`
- `seed`
- etc

## Examples
### Perform a prod run using the production credentials, from your laptop
(You wouldn't really do this, would you?)
``
$ dbt run --target prod
``

```
     
- Create separate articles for each global command option (the ones that go here: `$ dbt <option> <command>`
- Have better model selection syntax docs, probably move this to the `--models, --select, --exclude` article
- At some point, it might be worth pulling out some concepts into a separate section (a glossary? something else?). For example "threads" — this is part of `profiles.yml`, is a command line flag, and is part of a dbt Cloud "connection" (?). But where should the actual definition of "threads" live? Not sure! ¯\_(ツ)_/¯

**Comment by runleonarun** [comment]
Moving this idea to an [internal project](https://www.notion.so/dbtlabs/Content-Improvements-ae458c447cfa4eceb8b9d4eb33551654). We will reopen when this project is on our roadmap.
