### ISSUE TITLE
Create pages for each warehouse-specific config

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#252]
Each of these pages should be turned into a category instead.

<img width="296" alt="Screen Shot 2020-07-06 at 8 52 50 AM" src="https://user-images.githubusercontent.com/20294432/86595039-1c43db80-bf66-11ea-8c3b-da6c52a0d43e.png">

The config listed in each page should be made into separate pages.

Each config should:
- have a page for it, with description, default, usage examples etc.
- be listed/linked to on the relevant "model configurations", "snapshot configs" etc pages, to demonstrate the full gamut of configs a user can use
- be listed as a page in the in the "<warehouse>-specific configs"

**Comment by runleonarun** [comment]
This is low priority so adding the "icebox" label to come back to it when we can.
