### ISSUE TITLE
Finish off "unfinished" docs

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#255]
So, uh, there were some pages where I was like "yeah, I'll come back to those", and I have not yet.

They are:
- [materialized](https://docs.getdbt.com/reference/resource-configs/materialized) — this one is probably the most urgent
- [alias](https://docs.getdbt.com/reference/resource-configs/alias/)
- [schema](https://docs.getdbt.com/reference/resource-configs/schema/)
- [database](https://docs.getdbt.com/reference/resource-configs/database/)
- [sql_header](https://docs.getdbt.com/reference/resource-configs/sql_header/)

**Comment by runleonarun** [comment]
We're folding this into a reference section content improvement. project. Here's the [internal link](https://www.notion.so/dbtlabs/Restructure-References-section-v2-117eeee061274b0389022dcc927b61ee).
