### ISSUE TITLE
Better rendering for code blocks in reference section

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#261]
Ideas:
- Use **bold** to indicate required keys (e.g. `name:` in `dbt_project.yml`)
- Rather than using `< lt and gt signs >` to indicate that a value should be replaced (which is currently inconsistently used), render it with grey italics. Potentially with a more subtle hyperlink to a list of datatypes (?)

This will required changes to the "linky code  block" we've been using so far

**Comment by runleonarun** [comment]
We will answer these questions in a style guide. Stay tuned!
