### ISSUE TITLE
Fix home page button alignment

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#268]
The buttons are misaligned on docs.getdbt.com

<img width="1180" alt="Screen Shot 2020-07-08 at 1 34 50 PM" src="https://user-images.githubusercontent.com/20294432/86951727-e9ddde00-c11f-11ea-82a9-6a9fb167dd7d.png">

I don't think it always looked like this, but I'm not sure when it broke!

**Comment by runleonarun** [comment]
Looks fixed! 
<img width="1382" alt="Screen Shot 2021-12-13 at 11 12 55 AM" src="https://user-images.githubusercontent.com/3880403/145873676-c55aab58-4557-48d8-962d-def7ff170cc6.png">
