### ISSUE TITLE
Fix top bar resizing.

### ISSUE THREAD

**Issue by amychen1776** [dbt-labs/docs.getdbt.com#285]
## Steps to reproduce:
[1. Go to this link](https://docs.getdbt.com/dbt-cloud/api/)
2. Play around with the sizing of the window.

## Expected results:
For it to to the hamburger menu sooner. 

## Actual results
![image](https://user-images.githubusercontent.com/46451573/87474906-d6d07f80-c5f1-11ea-9558-e47bf2d15766.png)

## Extra details
N/A

**Comment by clrcrl** [comment]
Thanks @amychen1776!

@drewbanin, I'm going to assign this one to you.

I'd also be in favor of dropping those right-hand links so that this doesn't occur

**Comment by runleonarun** [comment]
Closing because I no longer see this. Feel free to reopen if I am wrong!
