### ISSUE TITLE
Feature: Better yaml highlighting

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#44]
The current YAML highlighting doesn't differentiate between keys and values.

In our docs:
<img width="723" alt="Screen Shot 2020-03-18 at 2 25 30 PM" src="https://user-images.githubusercontent.com/20294432/76994353-a1a67000-6924-11ea-8892-3f6f6485ac6d.png">

In my code editor:
<img width="460" alt="Screen Shot 2020-03-18 at 2 26 07 PM" src="https://user-images.githubusercontent.com/20294432/76994212-6e63e100-6924-11ea-9ea9-80865a882f4e.png">

**Comment by runleonarun** [comment]
Closing because it looks like we can leverage decent YAML highlighting beginneing code snippets with  
` ```yaml`

See it now:
<img width="870" alt="Screen Shot 2021-12-13 at 11 04 19 AM" src="https://user-images.githubusercontent.com/3880403/145872706-c4260a53-74ba-4753-99c6-20ea782563ae.png">
