### ISSUE TITLE
FAQ: Test before running the next model

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#68]
We get asked questions like this really often
<img width="329" alt="Screen Shot 2020-03-30 at 10 19 19 AM" src="https://user-images.githubusercontent.com/20294432/77923091-efe63800-726f-11ea-9f39-b370c3ed76ea.png">

**Comment by runleonarun** [comment]
I am closing this issue and putting it in the backlog. Labeled with "icebox" so we can revisit at a later date.
