### ISSUE TITLE
Bug: Previews show markdown instead of styled content

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/docs.getdbt.com#88]
## Steps to reproduce:
When I paste this URL in Slack:
https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas/

I get:
![image](https://user-images.githubusercontent.com/20294432/79139855-0a96d180-7d85-11ea-9c8e-d7764b7b73d6.png)

## Expected results:
Markdown links and headers should not show as raw markdown

## Actual results
Raw markdown is shown

**Comment by runleonarun** [comment]
I don't see this any longer. Please reopen if you do!
